### ISSUE TITLE
Deleted chat

### ISSUE THREAD

**Issue by l96alex** [tgicn/NightcoreIssues#11] opened 2015-09-29 00:46 UTC
Some other users were able to see deleted chat (Maybe just res dj's as well, not sure if this is intended or not) Also the way the line break works is slightly misleading now [Edit] Tested with a rdj account, they can see messages that are deleted with the button but not with a ! at the start. (https://gyazo.com/a7a0f3108da78ea0027ec9a72fcdd134) - Rdj on the left, bouncer on the right. (https://gyazo.com/71dcef58fa5de5cf0a925ce2ba76bb1e) - Grey user on the left. With it being greyed out but actually visible to users.

**Comment by Foorack** [comment] 2015-09-29 05:40
Thanks for reporting. Closing this as its a duplicate of #10.

**Closed by Foorack** 2015-09-29 05:40 UTC
